export * from './comment.interface';
export * from './commentDetails.interface';
export * from './user.interface';
export * from './userAddress.interface';
export * from './userDetails.interface';
export * from './post.interface';
export * from './postDetails.interface';
export * from './todos.interface';
export * from './todosDetails.interface';
